In [8]:
#sum of digits using recusion 
def sumOfNumber(n):
    assert n>=0 and int(n) == n,'the number must be a p[ositive integer '
    if n==0:
        return 0
    else:
        return int(n%10)+sumOfNumber(int(n/10))
print(sumOfNumber(12))

3


In [11]:
def powerOfNumber(base,exp):
    assert exp>=0 and int(exp)==exp,'the number must be an +ve integer'
    if exp==0:
        return 1
    if exp==1:
        return base
    else:
        return base*powerOfNumber(base,exp-1)
print(powerOfNumber(4,3))

64


In [15]:
def gcd(a,b):
    assert int(a)==a and int (b)==b,'the number must be +ve integer'
    if a<0:
        a=-1*a
    if b<0:
        b=-1*b
    if b==0:
        return a
    else:
        return gcd(b,a%b)
print(gcd(48,18))

6


In [2]:
def decimalToBinary(n):
    assert int(n)==n,'the number is always +ve number'
    if n==0:
        return 0
    else:
        return n%2 +10*decimalToBinary(int(n/2))
print(decimalToBinary(125))

1111101


In [7]:
def leap_year(year):
    assert int(year)==year,'the number iss +ve'
    if (year%4==0 and year%100!=0 or year%400==0):
        return leap_year
    else:
        return not_leap
print(leap_year(2004))

<function leap_year at 0x000000554CA760D8>


In [1]:
def fibonacci(n):
    assert n>=0 and int(n)==n,'the value is +ve integer '
    if n in [0,1]:
        return n
    else:
        return fibonacci(n-1)+fibonacci(n-2)
print(fibonacci(8))

21


In [2]:
def factorial(n):
    assert n>=0 and int(n)==n,'the number is always +ve and integer '
    if n in [0,1]:
        return n
    else:
        return n*factorial(n-1)
print(factorial(5))

120


In [3]:
from array import *
arr1 = array('i',[1,2,3,4,5,6])
print(arr1)

array('i', [1, 2, 3, 4, 5, 6])


In [4]:
#travesing of array
from array import*
arr1 = array('i',[1,2,3,4,5,6])
def traverseArray(array):
    for i in array:
        print(i)
traverseArray(arr1)

1
2
3
4
5
6


In [5]:
from array import *
arr1 = array('i',[1,2,3,4,5,6])
arr1.insert(6,7)
print(arr1)

array('i', [1, 2, 3, 4, 5, 6, 7])


In [10]:
from array import *
arr1 = array('i',[1,2,3,4,5,6])
def accessTheArray(array,index):
    if index>len(array):
        print("this element is not in the array")
    else:
        print(array[index])
        
accessTheArray(arr1,8)

this element is not in the array


In [14]:
from array import *
arr1 = array('i',[1,2,3,4,5,6])
def accessTheElement(array,value):
    for i in array:
        if i == value:
            return array.index(value)
    return "this value is not exist in the array"
accessTheElement(arr1,4)

3

In [2]:
#create an array and traverse
from array import *
my_array = array('i',[1,2,3,4,5,6])
for i in my_array:
    print(i)


1
2
3
4
5
6


In [3]:
#access individual element through index
from array import *
my_array=array('i',[1,2,3,4,5,6])
#append any value to the array using append()method
#my_array.append(7)
#insert a value using value by insert function
#my_array.insert(6,8)
my_array.extend([9])
print(my_array)



array('i', [1, 2, 3, 4, 5, 6, 9])


In [1]:
import numpy as np
twoDArray = np.array([[12,13,14,16],[22,33,44,55],[21,32,43,54],[13,24,35,46]])
print(twoDArray)

newTDArray = np.insert(twoDArray,1,[[1,2,3,4]],axis=1)
#newTDArray = np.append(twoDArray,[[2,3,4,5]],axis=0)
print(newTDArray)


[[12 13 14 16]
 [22 33 44 55]
 [21 32 43 54]
 [13 24 35 46]]
[[12  1 13 14 16]
 [22  2 33 44 55]
 [21  3 32 43 54]
 [13  4 24 35 46]]






## append any value to the array using append()method


In [5]:
import numpy as np
twoDArray = np.array([[12,13,14,16],[22,33,44,55],[21,32,43,54],[13,24,35,46]])
print(twoDArray)

def accessElement(array,rowindex,colindex):
    if rowindex>=len(array) and colindex>=len(array):
        print("this element is not exist")
    else:
        print(array[rowindex][colindex])

accessElement(twoDArray,0,4)
    

[[12 13 14 16]
 [22 33 44 55]
 [21 32 43 54]
 [13 24 35 46]]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [10]:
import numpy as np
oneArray=np.array([[12,11,10,9],[21,22,23,24],[31,32,33,34],[51,23,24,54]])
print(oneArray)
def traverseTwoDArray(array):
    for i in range (len(array)):
        for j in range (len(array)):
            print(array[i][j])
traverseTwoDArray(oneArray)
                    

[[12 11 10  9]
 [21 22 23 24]
 [31 32 33 34]
 [51 23 24 54]]
12
11
10
9
21
22
23
24
31
32
33
34
51
23
24
54


In [10]:
import numpy as np
oneArray=np.array([12,11,10,9],[21,22,23,24],[31,32,33,34],[51,23,24,54])
print(oneArray)
def accessElement(array,value):
    for i in range (len(array)):
        for j in range (len(array[0])):
            if i == value:
            return the value located here 
            'str[i]+" " +str[j]
             return "the element is not found"

SyntaxError: invalid syntax (<ipython-input-10-b1717a84107c>, line 8)

In [4]:
count=0
total = 0
while(True):
    inp = input("enter the number")
    if inp =='done':break
    value = float(inp)
    total = total+value
    count = count+1
    average = total/count
print('average',average)

enter the number1
enter the number2
enter the number3
enter the number4
enter the number5
enter the numberdone
average 3.0


In [7]:
myList=list()
while(True):
    inp = input("enter the number")
    if inp =='done':break
    value = float(inp)
    myList.append(value)
    average = sum(myList)/len(myList)
print('average',average)

enter the number1
enter the number2
enter the number3
enter the number4
enter the numberdone
average 2.5
